# Copyright 2026 TOPSBOT contributors.
# SPDX-License-Identifier: Apache-2.0
#
# Prepare a temporary HTTP root for python3 -m http.server so the browser can
# open http://<board>:8000/ without query params. Writes js/runtime_config.js
# from the active ROS params yaml (deployment / channel_count / ports).

import os
import shutil
import tempfile


def load_ros_params(path: str) -> dict:
    import yaml
    with open(path, 'r', encoding='utf-8') as handle:
        data = yaml.safe_load(handle) or {}
    return data.get('/**', {}).get('ros__parameters', data) or {}


def prepare_web_http_root(pkg_share: str, params: dict) -> str:
    """Copy share/web to a temp dir and inject runtime_config.js from params."""
    web_src = os.path.join(pkg_share, 'web')
    if not os.path.isdir(web_src):
        raise RuntimeError(f'webviz: web assets not found: {web_src}')

    root = tempfile.mkdtemp(prefix='topsbot_webviz_http_')
    for name in os.listdir(web_src):
        src = os.path.join(web_src, name)
        dst = os.path.join(root, name)
        if os.path.isdir(src):
            shutil.copytree(src, dst)
        else:
            shutil.copy2(src, dst)

    deployment = str(params.get('deployment', 'gateway')).strip() or 'gateway'
    channel_count = int(params.get('channel_count', 1))
    if channel_count < 1:
        channel_count = 1
    ws_base = int(params.get('ws_base_port', 8080))
    gateway_ws = int(params.get('gateway_ws_port', 9090))

    js_dir = os.path.join(root, 'js')
    os.makedirs(js_dir, exist_ok=True)
    runtime_path = os.path.join(js_dir, 'runtime_config.js')
    with open(runtime_path, 'w', encoding='utf-8') as handle:
        handle.write(
            '// Generated by topsbot_webviz launch — do not edit by hand.\n'
            'window.TopsbotWebvizRuntime = {\n'
            f"  mode: {deployment!r},\n"
            f'  maxChannels: {channel_count},\n'
            f'  ws_base_port: {ws_base},\n'
            f'  gateway_ws_port: {gateway_ws},\n'
            '};\n'
        )
    return root
